litecoin-foundation/loafwallet-ios

breadwallet.xcodeproj/project.pbxproj, breadwallet/src/ApplicationController.swift, breadwallet/src/Extensions/DispatchQueue+Additions.swift, breadwalletTests/LFWalletLockTest.swift
=> Fix: inputting last pincode lags

breadwallet/src/Constants/Strings.swift, breadwallet/src/ViewControllers/AboutViewController.swift
Updated the "About Us" where Charlie Lee is referenced
=> Add app store ref to Charlie

MessagesExtension/Info.plist, NotificationServiceExtension/Info.plist, TodayExtension/Info.plist, breadwallet WatchKit App/Info.plist, breadwallet WatchKit Extension/Info.plist, breadwallet.xcodeproj/project.pbxproj, breadwallet/Info.plist, breadwalletTests/Info.plist, breadwalletUITests/Info.plist
- fixes: codesigning issues
- bump version & resubmit to iTunes Connect
=> v2.0.5 (1)

loafwallet/src/ViewControllers/SecurityCenter/UpdatePinViewController.swift
on `Set Pin` screen, the instruction message `Your PIN will be used to unlock your Litewallet and send money.` is clipped.
=> Set Pin screen: fix instruction label clipped

Podfile, loafwallet/src/Constants/Constants.swift, loafwallet/src/ViewControllers/RootModals/SendViewController.swift
@mosadialiou  for fun and excitement
=> Kcw grunt/bugfix crashlytics

.gitignore, loafwallet.xcodeproj/project.pbxproj, loafwallet/Storyboards/Main.storyboard
@mosadialiou we are having a server issue with the Simplex endpoint
=> Kcw grunt/hotfix buy error

.github/bug_report.md, .github/feature_request.md, loafwallet.xcodeproj/xcshareddata/xcschemes/loafwallet WatchKit App.xcscheme
- Bug Report
- Feature Request
- Also have watch xcscheme added per upgrade
=> [Tech Debt] Added Issue templates

.github/bug_report.md, .github/feature_request.md, loafwallet.xcodeproj/xcshareddata/xcschemes/loafwallet WatchKit App.xcscheme
This PR represents tech debt changes required since V2.7.1
* fix crash: window required
* compute QR code only once - Import QR Fix
* run code on main thread - Analyzer recommendations
* update cocoapods firebase
* update addresses + event
* version bump
* remove unused fonts - DMCA violation fix
* Updated key for RemoteRunnable in xcscheme
=> [Merge to Master] Develop with tech debt improvements

loafwallet.xcodeproj/project.pbxproj, loafwallet/TransactionTableViewCells.swift, loafwallet/src/FlowControllers/StartFlowPresenter.swift, loafwallet/src/SimpleRedux.swift, loafwallet/src/SimpleRedux/Actions.swift, loafwallet/src/SimpleRedux/State.swift, loafwallet/src/ViewControllers/ConfirmationViewController.swift, loafwallet/src/ViewModels/Amount.swift, loafwalletTests/Legacy BRTests/TouchIdEnabledTests.swift
Reverts litecoin-foundation/loafwallet-ios#147
=> Revert "[Bugfix] Renamed enum from State"

loafwallet.xcodeproj/project.pbxproj, loafwallet/SupportLitecoinFoundationView.swift, loafwallet/SupportSafariView.swift, loafwallet/src/Constants/Constants.swift, loafwallet/src/ViewControllers/RootModals/SendViewController.swift
Bring develop in line with master branch
=> [Merge v2.8.3] into Develop

loafwallet/src/ModalPresenter.swift
There are leftover conflict markers that were immaterial to the operation of the app but needed to be removed
=> [Bugfix] Conflict fix

loafwallet.xcodeproj/project.pbxproj, loafwallet/Storyboards/Main.storyboard, loafwallet/TabBarViewController.swift
Litecoin Card lib not ready
- hide card tab
=> [HOTFIX] Hide Card Tab

loafwallet.xcodeproj/project.pbxproj, loafwallet/UnstoppableDomainView.swift, loafwallet/UnstoppableDomainViewModel.swift
=> [Merge into Develop] Release v3.1.1

loafwallet/BuyTableViewController.swift, loafwallet/BuyWKWebViewController.swift, loafwallet/Currency.swift, loafwallet/Storyboards/Buy.storyboard, loafwallet/src/Platform/BRWebViewController.swift
Allow more users the options for fiats
Before | After
-------|-----
=> [Feature] Simplex: Add more fiat pairs

Podfile, loafwallet.xcodeproj/project.pbxproj, loafwallet.xcodeproj/xcshareddata/xcschemes/loafwallet.xcscheme, loafwallet.xcworkspace/xcshareddata/swiftpm/Package.resolved
The previously committed Swift Package from Firebase works in build and run mode but it does not archive.
This is obviously a serious problem. 
Revert to cocoapods to keep using Firebase
=> [Bugfix] Firebase Swift package does not archive

loafwallet/Storyboards/Main.storyboard
The Face ID button sometimes triggers the other Forgot button
=> [Bugfix] Face ID hit area wrong.

loafwallet/BuyTableViewController.swift, loafwallet/BuyWKWebViewController.swift
The buy API served web page is cropped
Toggle the features of the latest WKWebview
|Fix|
|----|
|![afterwebwkview](https://user-images.githubusercontent.com/2899463/105922656-f6ca0c80-6032-11eb-89c5-23ed4e7c4c8b.gif)|
=> [Bugfix] Fix buywebview

loafwallet.xcodeproj/project.pbxproj, loafwallet.xcworkspace/xcshareddata/swiftpm/Package.resolved, loafwallet/Storyboards/Main.storyboard, loafwallet/TabBarViewController.swift
=> [Merge v3.2.0] into Develop

loafwallet/BuyTableViewController.swift, loafwallet/src/Controls/MenuButtonType.swift, loafwallet/src/ModalPresenter.swift, loafwallet/src/ViewControllers/RootModals/MenuViewController.swift
To allow users to have self service
- Renamed the types
- cleaned up old code
- added HC Url
|Before| After|
|-------|-----|
|![customeremail](https://user-images.githubusercontent.com/2899463/108207310-7c674680-711f-11eb-82c3-9a862ffb63f1.png)|![HCGif](https://user-images.githubusercontent.com/2899463/108207176-4b871180-711f-11eb-8cd2-5b9c226b3f1b.gif)|
=> [Feature] Added SFSafariViewController for Support

loafwallet/Storyboards/Main.storyboard, loafwallet/TabBarViewController.swift, loafwallet/src/Constants/Strings.swift, loafwallet/src/Strings/Base.lproj/Localizable.strings, loafwallet/src/Strings/da.lproj/Localizable.strings, loafwallet/src/Strings/de.lproj/Localizable.strings, loafwallet/src/Strings/en.lproj/Localizable.strings, loafwallet/src/Strings/es.lproj/Localizable.strings, loafwallet/src/Strings/fr.lproj/Localizable.strings, loafwallet/src/Strings/id.lproj/Localizable.strings, loafwallet/src/Strings/it.lproj/Localizable.strings, loafwallet/src/Strings/ja.lproj/Localizable.strings, loafwallet/src/Strings/ko.lproj/Localizable.strings, loafwallet/src/Strings/nl.lproj/Localizable.strings, loafwallet/src/Strings/pt.lproj/Localizable.strings, loafwallet/src/Strings/ru.lproj/Localizable.strings, loafwallet/src/Strings/sv.lproj/Localizable.strings, loafwallet/src/Strings/zh-Hans.lproj/Localizable.strings, loafwallet/src/Strings/zh-Hant.lproj/Localizable.strings
=> [Tech Debt] Added “Balance” label with localizations

loafwallet.xcodeproj/project.pbxproj, loafwallet/CHANGELOG.md, loafwallet/CardV1ToastView.swift, loafwallet/CardView.swift, loafwallet/View+Extension.swift, loafwallet/src/Constants/Strings.swift, loafwallet/src/Strings/Base.lproj/Localizable.strings, loafwallet/src/Strings/da.lproj/Localizable.strings, loafwallet/src/Strings/de.lproj/Localizable.strings, loafwallet/src/Strings/en.lproj/Localizable.strings, loafwallet/src/Strings/es.lproj/Localizable.strings, loafwallet/src/Strings/fr.lproj/Localizable.strings, loafwallet/src/Strings/id.lproj/Localizable.strings, loafwallet/src/Strings/it.lproj/Localizable.strings, loafwallet/src/Strings/ja.lproj/Localizable.strings, loafwallet/src/Strings/ko.lproj/Localizable.strings, loafwallet/src/Strings/nl.lproj/Localizable.strings, loafwallet/src/Strings/pt.lproj/Localizable.strings, loafwallet/src/Strings/ru.lproj/Localizable.strings, loafwallet/src/Strings/sv.lproj/Localizable.strings, loafwallet/src/Strings/zh-Hans.lproj/Localizable.strings, loafwallet/src/Strings/zh-Hant.lproj/Localizable.strings
- Adds a alert/toast that shows when the user taps on `Card`
- Adds localizations
|Clip|
|-----|
|![carddisclamer](https://user-images.githubusercontent.com/2899463/110049105-10a0f280-7d49-11eb-825a-572770e9ac6f.gif)|
=> 🦺[Tech debt] Add card disclaimer toast 

loafwallet.xcodeproj/project.pbxproj, loafwallet/RegistrationViewModel.swift
Users of version 1 had an issue with the password blocking the password making them unable to login to Litecoin Card .
Open the range to a wide number `24`
=> [Bugfix] Opened the password range: 24 chars

loafwallet.xcodeproj/project.pbxproj, loafwallet/EmptyTableViewCell.swift, loafwallet/Storyboards/Transactions.storyboard, loafwallet/TransactionsViewController.swift
- Makes sure the indexPath never violates the transaction array index
This keeps the selection within the range
#246
=> Bugfix: checks range.

loafwallet/TransactionsViewController.swift
- Used the blocktime change to update the label when syncing
- Add a test and use a ratio instead for the progress view
- Added more notes on methods
- Added helper method to return a progress value
- Reordered the method comments
|Before|After|
|------|------|
|![SyncFrozen-iOS](https://user-images.githubusercontent.com/2899463/112826657-31791100-9085-11eb-86d6-a65dfca07c8f.gif)|![bugfix-sync](https://user-images.githubusercontent.com/2899463/112828264-65553600-9087-11eb-8431-fca99ea6bc87.gif)|
=> Bugfix: Fixing animation of sync

Podfile, loafwallet.xcodeproj/project.pbxproj
Upgrade from UD [Cocoapod](cocoapods.org) 
`v0.1.6` to `v0.3.0`
=> 🦺[Tech Debt] upgraded the Unstoppable Domains pod to v0.3.0

loafwallet.xcodeproj/project.pbxproj, loafwallet.xcworkspace/xcshareddata/swiftpm/Package.resolved, loafwallet/AnimatedCardViewModel.swift, loafwallet/BuyTableViewController.swift, loafwallet/CardLoggedInView.swift, loafwallet/CardViewController.swift, loafwallet/CardViewModel.swift, loafwallet/CardWalletDetails.swift, loafwallet/src/Constants/Constants.swift, loafwallet/src/Strings/Base.lproj/Localizable.strings, loafwalletTests/Class Tests/LitecoinCardTests/CardWalletTests.swift
When the user logs into LitecoinCard, the balance is retrieved and updated in the CardLoggedInView
Closes #242 
- Added wallet detail and live balance
- Cleaned up the dev notes & response reference
- Add model using Codable
- Added test to check the wallet details
- Updated the text action
|Before|After|
|-----|-------|
|![beforelivebalance](https://user-images.githubusercontent.com/2899463/113520566-dd41c580-958b-11eb-8527-66c3b385f90a.gif)|![afterlivebalance](https://user-images.githubusercontent.com/2899463/113520574-e763c400-958b-11eb-9972-b6367f0f4fe9.gif)|
=> 🥳[Feature] Add live balance

loafwallet/ForgotAlertViewModel.swift, loafwallet/ForgotView.swift
Added a dismiss button for the reset password modal 
|Before|After|
|-------|------|
|![reset-password-after](https://user-images.githubusercontent.com/2899463/113770261-d5179080-9719-11eb-8386-c515fc6c5fa3.gif)|![new-reset-dismiss](https://user-images.githubusercontent.com/2899463/113770584-317ab000-971a-11eb-8ff2-44fb8451f634.gif)|
Closes #258
=> 🥳[Feature] Added dismiss button

loafwallet.xcodeproj/project.pbxproj, loafwallet/AnimatedCardViewModel.swift, loafwallet/BuyWKWebViewController.swift, loafwallet/CardViewController.swift, loafwallet/CardViewModel.swift, loafwallet/ForgotView.swift, loafwallet/RegistrationViewModel.swift, loafwallet/TransactionsViewController.swift, loafwallet/UnstoppableDomainViewModel.swift, loafwallet/src/Constants/Strings.swift, loafwallet/src/ModalPresenter.swift, loafwallet/src/Strings/ru.lproj/Localizable.strings, loafwallet/src/Views/AlertView.swift
- Added Moonpay 
- Added UD Error Codes
- Bugfixes
- Fixed transactions full sync freeze
- Opened Card Login password range
- Tech Debt: Polishes
- Upgraded UD version to 0.3.5
=> 🚀 [Release v3.4.0] Merge into Develop
